
services:
  db:
    image: postgres:13
    container_name: postgres_book
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpassword
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - book-network

  redis:
        image: redis:7-alpine
        container_name: redis_book
        ports:
             - "6379:6379"
        networks:
            - book-network


  app:
    image: golang:1.23
    container_name: book-app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=bookuser
      - DB_PASSWORD=bookpassword
      - DB_NAME=bookdb
      - REDIS_ADDR=redis:6379
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "
      go mod tidy &&
      go run cmd/main.go
      "
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - book-network



volumes:
  postgres_data:

networks:
  book-network:
    driver: bridge
